---
- name: configuracio IP
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Canviar IP
      copy:
      dest: /etc/netplan/50-cloud-init.yaml
        content: | 
          network:
            ethernets:
                enp1s0:
                    dhcp4: false
                    addresses: 192.168.10.1/24
                enp2s0:
                    dhcp4: true
             version: 2

